### PR TITLE
Implemented validation for Registration credentials. 

### PR DESCRIPTION
**Pull request by OmkarPh**
Hi @HyperLoo 
I worked out the validation of credentials for Registration router using Regular Expressions.
I didn't use any third party library.
I tried a decent number of test cases and chose best possible Regular expressions as well as error messages to serve the purpose.

Have a look and tell me if there is any  improvement. 

Happy Hacktoberfest

### CODE REVIEW

**Comment by hyperloo** [comment]
Hey @OmkarPh.
The validation is fine. I am merging the PR.

**Comment by HyperLoo** [comment]
Hey @OmkarPh , don't forget to ⭐ the repo!😁

**Comment by OmkarPh** [comment]
Starred and watched too !

Maybe I can contribute in your repos in future too 😁

Checkout my profile also, it's just a beginner level, but you can always give suggestions 😉

**Comment by hyperloo** [comment]
Thanks! Mine also is not much professional 😅, just seems to have many repos due to hosting requirements. Ya but keep learning and hosting join any of the societies that let you learn and contribute to them. This will really add up to your knowledge as well. All the best! 👍

**Comment by OmkarPh** [comment]
Hi @HyperLoo 
Sorry to bother you again but, I saw a new hacktoberfest guideline, it says that repo owner should this topic, "hacktoberfest" in order to let it's contributions being counted
image

I request you to add this topic "hacktoberfest" to this repo, coz I have this PR in my counting, otherwise it won't be counted

**Comment by hyperloo** [comment]
Yaa sure

**Pull request merged**
