### PR TITLE
Secured Node.js application from XSS

### PR DESCRIPTION
**Pull request by ryzbaka**
Used 2 npm packages:
* `xss-clean` : For sanitizing user input.
* `helmet.js`'s Content Security Policy : Middleware for cross-scripting mitigation.

### CODE REVIEW

**Comment by ryzbaka** [comment]
The PR is a response to the issue : https://github.com/HyperLoo/TaskManager-Server/issues/1

**Comment by hyperloo** [comment]
Hey @ryzbaka,
Please remove package-lock.json file. It will be auto-generated after yarn start.

**Comment by ryzbaka** [comment]
@HyperLoo , done.

**Comment by HyperLoo** [comment]
Merged, Don't forget to star the repo 😁

**Comment by ryzbaka** [comment]
Sure thing.

**Comment by HyperLoo** [comment]
Hey one more thing, how you search for the issues which are worth working on.

**Pull request merged**
